### ISSUE TITLE
Allow users a choice in dependencies.

### ISSUE THREAD

**Issue by keplersj** [steelbrain/package-deps#24] opened 2015-11-08 18:26 UTC
We are beginning to see a rise in Atom packages which provide different implementations for the same service, or differing grammars which provide highlighting differently.

In order to combat this packages should be able to designate an array of packages they are compatible with and depend on, but only one of the array should be picked.

An example manifest:

``` json
{
  "packageName": "linter-swiftc",
  "package-deps": [
    ["linter", "nuclide-diagnostics"],
    ["language-swift", "language-sourcekit"]
  ]
}
```

In this scenario when a user tries to install `linter-swiftc` they will be asked if they prefer `linter` or `nuclide-diagnostics`, and `language-swift` or `language-sourcekit`.

As well `package-deps` could detect if one of the options is installed before-hand and ignore asking in the first place.

**Comment by jamen** [comment] 2015-11-08 18:41
I think the idea is good, but the implementation you're explaining is missing a few things.

If there is someone who is not very knowledgeable in the atom community yet, they don't necessary know which packages match up with which...

Say if you presented the user with the option to choose two different linters and they install one, and then next you let the user choose two different packages that use each linter accordingly. If they miss match it wont work properly.

There needs to be a bit more functionality in the guidance process.

Otherwise I think the encompassing idea is good.

**Comment by Arcanemagus** [comment] 2015-12-28 23:06
This is essentially a duplicate of https://github.com/atom/apm/pull/387, but then this entire package will be superceded by that PR once it finally gets finished landing and released :wink:.

**Comment by steelbrain** [comment] 2016-02-08 14:33
Closing as the purpose of this package is very focused. For features like this one, we expect a full implementation from the Atom folks

**Comment by mallardduck** [comment] 2019-06-25 18:08
@steelbrain given that the expected implementation in Atom fell thru, could this concept be reconsidered?

**Comment by steelbrain** [comment] 2019-06-25 18:11
Very well, the JSON manifest API looks good enough in original issue. Any proposals for the UI? How should the user be able to select through the options? Radios/Select?

**Comment by mallardduck** [comment] 2019-06-25 18:21
I think simple would be best - either radios or select would be great.

From a UX perspective doing a Radio for 2-3 and select for 4+ might be cool. This way items that have 2-3 are really quick and simple; while items that use 4+ would be neatly organized. However I could see where the differing UI might be confusing - so with that in mind, the select option seems most universal.

Quick mock up of each:

![Screen Shot 2019-06-25 at 2 18 51 PM](https://user-images.githubusercontent.com/619938/60123018-78213500-9754-11e9-9975-975c5836ee34.png)
![Screen Shot 2019-06-25 at 2 16 18 PM](https://user-images.githubusercontent.com/619938/60123019-78213500-9754-11e9-9641-e28a63d9ec8b.png)

**Comment by mallardduck** [comment] 2019-06-25 18:35
Here are a few more mockups for the UI...

## Same as above with multiple dependencies:
![Screen Shot 2019-06-25 at 2 26 57 PM](https://user-images.githubusercontent.com/619938/60123832-545eee80-9756-11e9-9607-4ec49b5a1c6d.png)
![Screen Shot 2019-06-25 at 2 29 00 PM](https://user-images.githubusercontent.com/619938/60123834-545eee80-9756-11e9-8f4d-b5e7c21d7043.png)

## Multiple dependencies Alternative layout:
![Screen Shot 2019-06-25 at 2 32 49 PM](https://user-images.githubusercontent.com/619938/60123866-650f6480-9756-11e9-9885-0ca857561404.png)
![Screen Shot 2019-06-25 at 2 33 44 PM](https://user-images.githubusercontent.com/619938/60123867-650f6480-9756-11e9-8122-66279f81efba.png)

**Closed** 2020-08-16 17:17 UTC

**Comment by steelbrain** [comment] 2020-08-17 01:34
Here's what I ended up going with

<img src="https://user-images.githubusercontent.com/4278113/90339581-26e49c80-e00b-11ea-9488-fb5d64ee3f28.png" />
