### ISSUE TITLE
Unable to get loaded package

### ISSUE THREAD

**Issue by cponcelets** [steelbrain/package-deps#75] opened 2017-02-06 13:48 UTC
I tried to use package-deps to install an apm package for a theme.
However, an error message is printed on the console during the theme load.

[Package-Deps] Unable to get loaded package 'atom-antescofo'

Did I miss something ?

**Comment by steelbrain** [comment] 2017-02-06 13:51
Hi @cponcelets, it looks like you might be using this package incorrectly.

If I had to guess, you are passing the name of the package **to install** to the `.install()` function, however, this package requires you to put that package's name in your package.json's `package-deps` and call `.install()` with the name of the package that's trying to install

**Comment by cponcelets** [comment] 2017-02-06 17:48
Hi @steelbrain, thank you for answering so fast.
I didn't detailed but I do.
Here is the part of my package.json and the index.js (sorry for omitting):

package.json:
`  "dependencies": {
    "atom-package-deps": "*"
  },
  "package-deps": [
    "atom-antescofo"
  ],`

index.js:
`'use babel'

module.exports = {
  activate() {
    require('atom-package-deps').install('atom-antescofo')
      .then(function() {
        console.log('All dependencies installed, good to go')
      })
  }
}
`
I'm on a Os X El Capitain v10.11.6.

**Comment by steelbrain** [comment] 2017-02-06 17:50
@cponcelets your manifest is correct, but your line `require('atom-package-deps').install('atom-antescofo')` should have the name of your package, not the package you want to install.

**Comment by cponcelets** [comment] 2017-02-06 18:10
ok :)
Seems to be the same with my own package name.
(I replaced with )
`'use babel'

module.exports = {
  activate() {
    require('atom-package-deps').install('atom-antescofo-syntax')
      .then(function() {
        console.log('All dependencies installed, good to go')
      })
  }
}`
which is the name of my package.

**Comment by steelbrain** [comment] 2017-02-07 11:07
@cponcelets is your package open source? Can you show us the `package.json`'s `name` value of your package?

**Comment by cponcelets** [comment] 2017-02-07 12:50
Of course, it is this github : https://github.com/nadirB/atom-antescofo-syntax.
The package name value is "atom-antescofo-syntax" (I guess ' ' or " " is the same, doesn't it ?).
And the package to install is there https://github.com/cponcelets/atom-antescofo/blob/v1.0.5-beta/package.json, name value "atom-antescofo".

Is the bug come from the fact that I want to install a package from a theme ?

**Comment by steelbrain** [comment] 2017-02-07 13:12
@cponcelets Your package is great. The code in it is correct. The problem is that Atom is designed to only activate themes when they are selected as active.

For example, if you remove `"theme": "syntax"` from your package's `package.json` file, it'll auto-install the parent theme. You can open an issue on Atom repository and ask for theme's package activation even before it's activated.

Closing as external, but feel free to continue discussing.

**Closed by steelbrain** 2017-02-07 13:12 UTC

**Comment by cponcelets** [comment] 2017-02-07 13:25
Ok, thank you very much steelbrain.
